name: GeoTest Framework CI

on:
  push:
    branches: [ engineering-quality ]
  pull_request:
    branches: [ engineering-quality ]
  schedule:
    # Daily regression runs at 02:00 UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  pull-requests: write
  actions: read
  security-events: write

jobs:
  # Smoke tests - Quick validation
  smoke-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      run: |
        docker compose build smoke-tests-ci
    
    - name: Run smoke tests and extract reports
      run: |
        # Run tests without auto-removal to keep container for report extraction
        container_id=$(docker compose run -d smoke-tests-ci)
        # Wait for tests to complete
        docker wait $container_id || true
        # Copy reports from the finished container
        docker cp $container_id:/app/reports ./reports || echo "No reports found in container"
        # Clean up the container
        docker rm $container_id || true
        # List what we extracted
        ls -la reports/ || echo "No reports directory created"
    
    - name: Upload smoke test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: reports/smoke-*
        retention-days: 30
    
    - name: Comment PR with smoke results
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request' && always()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          try {
            // Check if we have pull request context
            if (!context.issue || !context.issue.number) {
              console.log('No pull request context available');
              return;
            }
            
            const reportPath = 'reports/smoke-report.json';
            let body = '## Smoke Test Results\n\n';
            
            if (fs.existsSync(reportPath)) {
              const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
              const summary = report.summary || {};
              const status = summary.failed > 0 ? '❌ FAILED' : '✅ PASSED';
              body += `**Status:** ${status}\n\n`;
              body += `**Summary:**\n`;
              body += `- Passed: ${summary.passed || 0}\n`;
              body += `- Failed: ${summary.failed || 0}\n`;
              body += `- Total: ${summary.total || 0}\n`;
              body += `- Duration: ${report.duration || 'N/A'}s\n\n`;
              body += `View detailed results in the [artifacts](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).`;
            } else {
              body += '❌ No test report found. Check the workflow logs for details.';
            }
              
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
            
            console.log('Successfully posted PR comment');
          } catch (error) {
            console.log('Could not post smoke test results:', error.message);
            console.log('Error details:', error);
          }

  # Regression tests - Comprehensive validation
  regression-tests:
    runs-on: ubuntu-latest
    needs: smoke-tests
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[full-test]')
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      run: |
        docker compose build regression-tests-ci
    
    - name: Run regression tests and extract reports
      run: |
        # Run tests without auto-removal to keep container for report extraction
        container_id=$(docker compose run -d regression-tests-ci)
        # Wait for tests to complete
        docker wait $container_id || true
        # Copy reports from the finished container
        docker cp $container_id:/app/reports ./reports || echo "No reports found in container"
        # Clean up the container
        docker rm $container_id || true
        # List what we extracted
        ls -la reports/ || echo "No reports directory created"
    
    - name: Upload regression test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: regression-test-results
        path: reports/regression-*
        retention-days: 30

  # Full test suite - All tests
  full-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/engineering-quality' && github.event_name == 'push'
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image
      run: |
        docker compose build all-tests-ci
    
    - name: Run all tests and extract reports
      run: |
        # Run tests without auto-removal to keep container for report extraction
        container_id=$(docker compose run -d all-tests-ci)
        # Wait for tests to complete
        docker wait $container_id || true
        # Copy reports from the finished container
        docker cp $container_id:/app/reports ./reports || echo "No reports found in container"
        # Clean up the container
        docker rm $container_id || true
        # List what we extracted
        ls -la reports/ || echo "No reports directory created"
    
    - name: Upload full test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: full-test-results
        path: reports/all-*
        retention-days: 30
    
    - name: Check image size
      run: |
        IMAGE_SIZE=$(docker images geotest-framework-geotest --format "table {{.Size}}" | tail -n 1)
        echo "Docker image size: $IMAGE_SIZE"
        # Convert size to MB for comparison (basic check)
        if docker images --format "table {{.Size}}" geotest-framework-geotest | grep -E "^[2-9][0-9][0-9]MB|^[1-9]GB"; then
          echo "Warning: Image size might exceed 200MB target"
        fi

  # Security and quality checks
  security-scan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build test image for scanning
      run: |
        docker compose build geotest
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'geotest-framework-geotest:latest'
        format: 'sarif'
        output: 'trivy-results.sarif'
      continue-on-error: true
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('trivy-results.sarif') != ''
      with:
        sarif_file: 'trivy-results.sarif'